include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    avoid_print: false
    sort_pub_dependencies: false
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]
  errors:
    invalid_annotation_target: ignore
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    avoid_positional_boolean_parameters: ignore
