name: contentful_flutter
description: The Contentful Flutter SDK is a Dart package that allows you to access the Contentful Content Delivery API from your Flutter app.
version: 0.0.7
homepage: https://hackberry.se

environment:
  sdk: ">=2.19.0 <4.0.0"

dependency_overrides: 
  collection: ^1.17.2

dependencies:
  flutter:
    sdk: flutter
  # ... Code generation ...
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  # ... Network ...
  http: ^1.1.0
  retry: ^3.1.2
  fpdart: ^1.1.0 # Functional programming to use the Either<> type
  collection: ^1.18.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
  # ... Code generation ...
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  # ... Linting ...
  lints: ^3.0.0
